language: java
before_install: mvn install -DskipTests=true -DfinalName=helloworld-$TRAVIS_TAG
install: mvn test

deploy:
  provider: releases
  api_key:
    secure: NXPgczB7fzf+Y+vSNJfFXMc1/hnCHtDImgyYs4dFD/tmktgtQHRXNkm7rCziv4se3ZCWer9CdA/6X1lUp4HptdMqKtK+bGYi+ucIOAOfC6m+BNdEhwEnQTlvo3Rm52iOJm1bjK1xtvvFZKJg5J2k1cXiHFSanIRmONGiWXuqqkA=
  file: target/helloworld-$TRAVIS_TAG.war
  on:
    tags: true
